apiVersion: v1
kind: Service
metadata:
  labels:
    app: payment
  name: {{ .Chart.Name }}-payment-node-port
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: payment
  type: ClusterIP