apiVersion: v1
kind: Service
metadata:
  labels:
    app: notification
  name: {{ .Chart.Name }}-notification-node-port
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: notification
  type: ClusterIP