apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-config-map
data:
  HTTP_PORT: "3000"
  TCP_PORT: "3001"
  GRPC_URL: "notification:3001"
  ORDER_HOST: "order"
  ORDER_TCP_PORT: "3001"
  ORDER_GRPC_URL: "order:3001"