apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-notification-deployment
  labels:
    app: notification
spec:
  replicas: {{ .Values.notification.replicas }}
  selector:
    matchLabels:
      app: notification
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - image: songminkyu/fc-nestjs-notification:latest
          name: notification-container
          envFrom:
            - configMapRef:
                name: notification-config-map
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              port: 3000
              path: "/health"
            periodSeconds: 5
          readinessProbe:
            httpGet:
              port: 3000
              path: "/health"
            periodSeconds: 5




