apiVersion: v1
kind: Service
metadata:
  labels:
    app: product
  name: {{ .Chart.Name }}-product-cluster-ip
spec:
  ports:
    - port: 3001
      protocol: TCP
      targetPort: 3001
  selector:
    app: product
  type: ClusterIP