apiVersion: v1
kind: Pod
metadata:
  name: nginx-app
  labels:
    app: nginx-app
    type: back-end

spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80