apiVersion: v1
kind: Pod
metadata: 
  name: nginx-pod
  labels:
    app: nginx-app
    type: back-end
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80
      envFrom:
        - configMapRef:
            name: nginx-config