apiVersion: v1
kind: Service
metadata:
  labels:
    app: gateway
  name: {{ .Chart.Name }}-gateway-node-port
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: gateway
  type: NodePort