apiVersion: v1
kind: Service
metadata:
  labels:
    app: order
  name: {{ .Chart.Name }}-order-cluster-ip
spec:
  ports:
    - port: 3001
      protocol: TCP
      targetPort: 3001
  selector:
    app: order
  type: ClusterIP