apiVersion: v1
kind: Service
metadata:
  labels:
    app: order
  name: {{ .Chart.Name }}-order-node-port
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: order
  type: ClusterIP