apiVersion: v1
kind: Service
metadata:
  labels:
    app: user
  name: {{ .Chart.Name }}-user-node-port
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: user
  type: ClusterIP