apiVersion: v1
kind: ConfigMap
metadata:
  name: user-config-map
data:
  HTTP_PORT: "3000"
  TCP_PORT: "3001"
  GRPC_URL: "user:3001"
  REFRESH_TOKEN_SECRET: "codefactoryrefresh"
  ACCESS_TOKEN_SECRET: "codefactoryaccess"

