apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv
spec:
  capacity:
    storage: 1Mi
  accessModes:
    # ReadWriteOnce (RWO)-> Read Write Mode로 하나의 노드만 점유 가능
    # ReadOnlyMany (ROX) -> Read Only로 여러 노드 점유 가능
    # ReadWriteMany (RWX) -> Read Write Mode로 여러 노드 점유 가능 (NFS)
    - ReadWriteOnce
  hostPath:
    type: DirectoryOrCreate
    path: "/mnt/data"